spring.application.name=UberReviewService

spring.datasource.url=jdbc:mysql://localhost:3306/UberDB
spring.datasource.username=root
spring.datasource.password=ri0De7@nerio

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=7474
