spring.application.name=UberSocketServer
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.preferIpAddress=true
server.port=7480
server.address=0.0.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update