spring.application.name=UberAuthService

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=7475
server.address=0.0.0.0

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.preferIpAddress=true

jwt.expiry=604800000
jwt.secret=${JWT_SECRET}
