spring:
  application:
    name: UberLocationService

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      url: ${REDIS_URL}

server:
  address: 0.0.0.0
  port: 7477

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: true
